#!/bin/sh
# Copyright 2024 Huawei Cloud Computing Technology Co., Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# ensure all required outputs are present
touch stdout
touch stderr
RESULT=UNKNOWN
echo "${RESULT}" > result

export OUT="$(pwd)/out"
mkdir -p config
export CONFIG="$(pwd)/config"

cd work

if ../linter "$@" > ../stdout 2> ../stderr
then
    RESULT=PASS
else
    RESULT=FAIL
fi

echo "${RESULT}" > ../result

if [ "${RESULT}" '!=' PASS ]
then
   exit 1;
fi
